const fs = require('fs');
const say = require('say');
const Gen = require('sentence-generator');
const config = require('../config');
const utils = require('../utils');

const gen = Gen('./sentences.txt');

const sentence = {
  sentence: (message) => {
    message.delete(200);
    return message.channel.send({
      embed: {
        color: config.palette.pink,
        title: `\`\`\`\n${gen.take(1)}\n\`\`\``,
        description: `*Generated by ${message.author.username}*`
      }
    });
  },
  tts: (message) => {
    let sentence = gen.take(1);
    let author = message.author.username;
    message.delete(200);
    return message.channel.send(sentence, { tts: true }).then((message) => { message.edit(`:speech_balloon: *"${sentence}"*\n          — Generated by ${author}`); });
  },
  speak: (message) => {
    const voiceChannel = message.member.voiceChannel;
    if (!voiceChannel) {
      message.delete(200);
      return message.author.send({
        embed: {
          color: config.palette.red,
          title: `:warning: **You are not in a voice channel!**`,
          description: `I can't say your requested sentence as you're not in a voice channel. Please join a voice channel and then make your request again.`,
          fields: [
            {
              name: 'For reference, your request was:',
              value: `\`\`\`\n${message.content}\n\`\`\``
            }
          ]
        }
      });
    }
    voiceChannel.join()
      .then(connection => {
        var sentence = gen.take(1);
        let encoded = utils.encode(sentence);
        let filename = `./${config.paths.speech}/${encoded}.wav`;
        if (fs.existsSync(filename)) {
          connection.playFile(filename);
        } else {
          say.export(sentence, config.discord.voice, 1, filename, function (err) {
            if (err) { return console.error(err); }
            connection.playFile(filename);
          });
        }
        message.delete(200);
      });
  }
};

module.exports = sentence;
