const client = require("../discord/discord-client");
const Gen = require("sentence-generator");
const config = require("../config");

const gen = Gen("./sentences.txt");

const sentence = {
  sentence: (channelId, author, queueId, callback) => {
    if (channelId && author) {
      client.channels.get(channelId).send({
        embed: {
          color: config.palette.pink,
          title: `\`\`\`\n“${gen.take(1)}”\n\`\`\``,
          description: `*:writing_hand::skin-tone-2: Generated by ${author}*`
        }
      });
      setTimeout(() => {
        callback(null, { queueId: queueId });
      }, 2000);
    }
  },
  tts: (channelId, author, queueId, callback) => {
    if (channelId && author) {
      const sentence = gen.take(1);
      client.channels
        .get(channelId)
        .send(sentence, { tts: true })
        .then(message => {
          message.edit("", {
            embed: {
              color: config.palette.yellow,
              title: `\`\`\`\n“${sentence}”\n\`\`\``,
              description: `:speak_no_evil: *Generated by ${author}*`
            }
          });
        });
      setTimeout(() => {
        callback(null, { queueId: queueId });
      }, 2000);
    }
  }
};

module.exports = sentence;
