const client = require("../discord/discord-client");
const Gen = require("sentence-generator");
const config = require("../config");

const gen = Gen("./sentences.txt");

const sentence = {
  sentence: (message, channelId, author, queueId, callback) => {
    if (message) {
      message.delete(200);
      message.channel.send({
        embed: {
          color: config.palette.pink,
          title: `\`\`\`\n“${gen.take(1)}”\n\`\`\``,
          description: `*:writing_hand::skin-tone-2: Generated by ${
            message.author.username
          }*`
        }
      });
      setTimeout(() => {
        callback(null, { queueId: queueId });
      }, 2000);
    }

    if (channelId && author) {
      client.channels.get(channelId).send({
        embed: {
          color: config.palette.pink,
          title: `\`\`\`\n“${gen.take(1)}”\n\`\`\``,
          description: `*:writing_hand::skin-tone-2: Generated by ${author}*`
        }
      });
      setTimeout(() => {
        callback(null, { queueId: queueId });
      }, 2000);
    }
  },
  tts: (message, channelId, author, queueId, callback) => {
    if (message) {
      let sentence = gen.take(1);
      let messageAuthor = message.author.username;
      message.delete(200);
      message.channel.send(sentence, { tts: true }).then(message => {
        message.edit("", {
          embed: {
            color: config.palette.yellow,
            title: `\`\`\`\n“${sentence}”\n\`\`\``,
            description: `:speak_no_evil: *Generated by ${messageAuthor}*`
          }
        });
      });
      setTimeout(() => {
        callback(null, { queueId: queueId });
      }, 2000);
    }

    if (channelId && author) {
      const sentence = gen.take(1);
      client.channels
        .get(channelId)
        .send(sentence, { tts: true })
        .then(message => {
          message.edit("", {
            embed: {
              color: config.palette.yellow,
              title: `\`\`\`\n“${sentence}”\n\`\`\``,
              description: `:speak_no_evil: *Generated by ${author}*`
            }
          });
        });
      setTimeout(() => {
        callback(null, { queueId: queueId });
      }, 2000);
    }
  }
};

module.exports = sentence;
